[workspace]
resolver = "2"
members = [
  "contracts/*",
  "integration-tests",
  "packages/*",
]

[workspace.package]
edition = "2021"
rust-version = "1.76.0"

[workspace.dependencies]
soroban-sdk = { version = "20.2.0" }
axelar-soroban-interfaces = { version = "^0.1.0", path = "contracts/axelar-soroban-interfaces" }
axelar-soroban-std = { version = "^0.1.0", path = "packages/axelar-soroban-std" }
axelar-auth-verifier = { version = "^0.1.0", path = "contracts/axelar-auth-verifier" }
axelar-gas-service = { version = "^0.1.0", path = "contracts/axelar-gas-service" }
axelar-gateway = { version = "^0.1.0", path = "contracts/axelar-gateway" }
axelar-operators = { version = "^0.1.0", path = "contracts/axelar-operators" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
