coverage:
  status:
    project:
      default:
        target: 94%
        threshold: 0.25%
        informational: false
    patch:
      default:
        target: 94%
        threshold: 1%
        informational: false
  require_tests: true
