[package]
name = "axelar-soroban-std"
version = "0.1.0"
edition = { workspace = true }
description = "Contract related to Axelar Soroban Std."
license = "MIT OR Apache-2.0"
publish = true

[lib]
crate-type = ["rlib"]

[dependencies]
soroban-sdk = { workspace = true }

[features]
testutils = ["soroban-sdk/testutils"]

[lints]
workspace = true
