[package]
name = "axelar-soroban-std"
version = "0.1.0"
edition = { workspace = true }
description = "Contract related to Axelar Soroban Std."
license = "MIT"
publish = true

[lib]
crate-type = ["rlib"]

[dependencies]
axelar-soroban-std-derive = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
soroban-sdk = { workspace = true }

[dev-dependencies]
goldie = { workspace = true }
soroban-sdk = { workspace = true, features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils", "hex"]
derive = ["dep:axelar-soroban-std-derive"]

[lints]
workspace = true
