[package]
name = "axelar-soroban-std"
version = "0.1.0"
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
soroban-sdk = { workspace = true }

[features]
testutils = ["soroban-sdk/testutils"]

[lints]
workspace=true
