[package]
name = "axelar-gas-service"
version = "0.1.0"
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true, features = ["alloc"] }

[dev_dependencies]
soroban-sdk = { workspace = true, features = ["testutils", "alloc"] }
secp256k1 = { version = "0.28.2", features = ["recovery", "rand"] }

[features]
testutils = ["soroban-sdk/testutils"]
