[package]
name = "axelar-gateway"
version = "0.1.0"
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
axelar-auth-verifier = { workspace = true, optional = true }
axelar-soroban-interfaces = { workspace = true }
rand = { version = "0.8.5", optional = true }
soroban-sdk = { workspace = true }

[dev_dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
axelar-auth-verifier = { workspace = true, features = ["testutils"] }
axelar-soroban-std = { workspace = true, features = ["testutils"] }
rand = { version = "0.8.5" }

[features]
default = ["axelar-auth-verifier"]
testutils = ["soroban-sdk/testutils", "axelar-auth-verifier/testutils", "axelar-soroban-std/testutils", "rand"]
