[package]
name = "stellar-axelar-std"
version = "0.2.0"
edition = { workspace = true }
description = "Contract related to Axelar Std."
license = { workspace = true }
publish = true

[lib]
crate-type = ["rlib"]

[dependencies]
hex = { workspace = true, optional = true }
soroban-sdk = { workspace = true }
soroban-token-sdk = { workspace = true }
stellar-axelar-std-derive = { workspace = true, optional = true }

[dev-dependencies]
goldie = { workspace = true }
hex = { workspace = true }
paste = { workspace = true }
soroban-sdk = { workspace = true, features = ["testutils"] }
stellar-axelar-std-derive = { workspace = true, features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils", "hex", "stellar-axelar-std-derive/testutils"]
derive = ["dep:stellar-axelar-std-derive"]

[lints]
workspace = true
