[package]
name = "stellar-axelar-std"
version = "1.0.0"
edition = { workspace = true }
description = "Standard libraries for Axelar contracts."
license = { workspace = true }
publish = true

[lib]
crate-type = ["rlib"]

[dependencies]
goldie = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
soroban-sdk = { workspace = true }
stellar-axelar-std-derive = { workspace = true, optional = true }

[dev-dependencies]
goldie = { workspace = true }
hex = { workspace = true }
paste = { workspace = true }
soroban-sdk = { workspace = true, features = ["testutils"] }
stellar-axelar-std-derive = { workspace = true }

[features]
testutils = ["soroban-sdk/testutils", "dep:hex", "dep:goldie", "dep:serde"]
derive = ["dep:stellar-axelar-std-derive"]
alloc = ["soroban-sdk/alloc"]

[lints]
workspace = true
