[package]
name = "stellar-axelar-std-derive"
version = "1.0.0"
edition = { workspace = true }
description = "Proc macros for Axelar contracts."
license = { workspace = true }
publish = true

[lib]
proc-macro = true

[features]

[dependencies]
goldie = { workspace = true }
heck = "0.5"
prettyplease = "0.2"
proc-macro2 = { workspace = true }
quote = { version = "1.0", default-features = false }
syn = { version = "2.0", features = ["full", "extra-traits"] }

[dev-dependencies]

[lints]
workspace = true
