[package]
name = "stellar-axelar-std-derive"
version = "1.0.0"
edition = { workspace = true }
description = "Proc macros for Axelar contracts."
license = { workspace = true }
publish = true

[lib]
proc-macro = true

[features]

[dependencies]
heck = "0.5"
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
