[package]
name = "axelar-soroban-interfaces"
version = "0.1.0"
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
axelar-soroban-std = { workspace = true }
soroban-sdk = { workspace = true }

[dev-dependencies]
goldie = { version = "0.5" }
hex = "0.4"
hex-literal = "0.4"
