name: Setup Stellar CLI
description: 'Setup Stellar CLI'

inputs:
  stellar-version:
    description: 'The version of Stellar CLI to install'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Cache Stellar binaries
      id: cache-stellar
      uses: actions/cache@v4
      with:
        path: stellar-binaries/
        key: stellar-${{ inputs.stellar-version }}

    - name: Install Dependencies
      shell: bash
      if: steps.cache-stellar.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y libsodium23

    - name: Download and Install Stellar
      shell: bash
      if: steps.cache-stellar.outputs.cache-hit != 'true'
      run: |
        mkdir -p stellar-binaries
        curl -L -o stellar-cli-${{ inputs.stellar-version }}-x86_64-unknown-linux-gnu.tar.gz https://github.com/stellar/stellar-cli/releases/download/v${{ inputs.stellar-version }}/stellar-cli-${{ inputs.stellar-version }}-x86_64-unknown-linux-gnu.tar.gz
        curl -L -o soroban-cli-${{ inputs.stellar-version }}-x86_64-unknown-linux-gnu.tar.gz https://github.com/stellar/stellar-cli/releases/download/v${{ inputs.stellar-version }}/soroban-cli-${{ inputs.stellar-version }}-x86_64-unknown-linux-gnu.tar.gz | true
        tar -xvf stellar-cli-${{ inputs.stellar-version }}-x86_64-unknown-linux-gnu.tar.gz -C stellar-binaries
        tar -xvf soroban-cli-${{ inputs.stellar-version }}-x86_64-unknown-linux-gnu.tar.gz -C stellar-binaries | true
        rm -rf stellar-cli-${{ inputs.stellar-version }}-x86_64-unknown-linux-gnu.tar.gz
        rm -rf soroban-cli-${{ inputs.stellar-version }}-x86_64-unknown-linux-gnu.tar.gz | true

    - name: Save Stellar binaries
      if: steps.cache-stellar.outputs.cache-hit != 'true'
      id: cache-stellar-save
      uses: actions/cache@v4
      with:
        path: stellar-binaries/
        key: stellar-${{ inputs.stellar-version }}

    - name: Add Stellar binaries to PATH
      shell: bash
      run: |
        sudo cp ./stellar-binaries/stellar /usr/local/bin/stellar
        sudo cp ./stellar-binaries/soroban /usr/local/bin/soroban | true
