name: Compile Stellar CLI
description: 'Compile Stellar CLI'

inputs:
  stellar-version:
    description: 'The version of Stellar CLI to compile'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Cache Stellar binaries
      id: cache-stellar
      uses: actions/cache@v4
      with:
        path: stellar-binaries/
        key: stellar-${{ inputs.stellar-version }}

    - name: Checkout Stellar CLI Repo
      uses: actions/checkout@v4
      with:
        repository: "stellar/stellar-cli"
        path: stellar-cli
        fetch-depth: "0"
        ref: main

    - name: Compile & Install Stellar CLI
      shell: bash
      if: steps.cache-stellar.outputs.cache-hit != 'true'
      working-directory: ./stellar-cli
      run: cargo install "stellar-cli@${{ inputs.stellar-version }}" --features opt

    - name: Copy binaries
      shell: bash
      if: steps.cache-stellar.outputs.cache-hit != 'true'
      run: |
        mkdir -p ./stellar-binaries
        cp "$HOME/.cargo/bin/stellar" ./stellar-binaries/stellar
        chmod +x ./stellar-binaries/stellar

    - name: Save Stellar binaries
      if: steps.cache-stellar.outputs.cache-hit != 'true'
      id: cache-stellar-save
      uses: actions/cache@v4
      with:
        path: stellar-binaries/
        key: stellar-${{ inputs.stellar-version }}

    - name: Add Stellar binaries to PATH
      shell: bash
      run: |
        sudo cp ./stellar-binaries/stellar /usr/local/bin/stellar
