name: Compile

on:
  pull_request:
  push:
    branches:
      - main
      - releases/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  soroban-compilation:
    name: Soroban Compilation
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0
          targets: wasm32-unknown-unknown

      - name: Rust Cache
        uses: useblacksmith/rust-cache@v3.0.1
        with:
          shared-key: "cache-compilation"

      - name: Build wasm release
        run: cargo wasm
