name: Contract Storage Schema Migration Check

on: pull_request

jobs:
  check-migration:
    name: Check Valid Migration File Exists
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for storage schema changes
        run: |
          chmod +x .github/scripts/check-migration.sh

          .github/scripts/check-migration.sh ${{ github.event.pull_request.base.sha }} ${{ github.sha }}
