name: Linting

on:
  pull_request:
  push:
    branches:
      - releases/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lints:
    name: Lints
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.81.0
          override: true
          components: rustfmt, clippy

      - name: Cache build artifacts
        uses: useblacksmith/rust-cache@v3
        with:
          shared-key: "cache"

      - name: Install cargo-sort
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-sort

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo sort
        uses: actions-rs/cargo@v1
        with:
          command: sort
          args: --workspace --check --check-format

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Check Diff
        # fails if any changes not committed
        run: git diff --exit-code
