name: Lint

on:
  pull_request:
  push:
    branches:
      - main
      - releases/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lints:
    name: Lints
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0
          components: rustfmt, clippy

      - name: Rust Cache
        uses: useblacksmith/rust-cache@v3
        with:
          shared-key: "cache"

      - name: Install cargo-sort
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-sort

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo sort
        run: cargo-sort --workspace --check --check-format

      - name: Run cargo clippy
        run: cargo clippy --workspace --all-targets --all-features --fix -- -D warnings

      - name: Check for uncommitted changes
        run: git diff --exit-code
