name: Lint

on:
  pull_request:
  push:
    branches:
      - main
      - releases/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lints:
    name: Lints
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0
          components: clippy

      - name: Rust Cache
        uses: useblacksmith/rust-cache@v3.0.1
        with:
          shared-key: "cache-lint"

      - name: Install cargo-sort
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-sort

      - name: Run cargo sort
        run: cargo-sort --workspace --check --check-format

      - name: Run cargo clippy (no features)
        run: cargo clippy --workspace --no-default-features --allow-dirty --fix -- -D warnings

      - name: Run cargo clippy (all features)
        run: cargo clippy --workspace --all-features --allow-dirty --fix -- -D warnings

      - name: Run cargo doc
        run: cargo doc --no-deps --workspace

      - name: Check for uncommitted changes
        run: git diff --exit-code
