name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Suite
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0

      - name: Rust Cache
        uses: useblacksmith/rust-cache@v3
        with:
          shared-key: "cache"

      - name: Run tests for contracts
        run: for C in contracts/*; do cd $C && RUSTFLAGS="-D warnings" cargo test --locked && cd ..; done
        env:
          RUST_BACKTRACE: 1

      - name: Run tests for packages
        run: for C in packages/*; do cd $C && RUSTFLAGS="-D warnings" cargo test --locked && cd ..; done
        env:
          RUST_BACKTRACE: 1

      - name: Remove all golden files
        run: find . -name "*.golden" -exec rm -rf {} \;

      - name: Regenerate golden files
        run: RUSTFLAGS="-D warnings" cargo test --locked
        env:
          GOLDIE_UPDATE: 1

      - name: Check for stale golden files
        run: git diff --exit-code
